# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagina_inicial = QtWidgets.QWidget()
        self.pagina_inicial.setObjectName("pagina_inicial")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pagina_inicial)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout1 = QtWidgets.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnProfessor = QtWidgets.QPushButton(self.pagina_inicial)
        self.btnProfessor.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnProfessor.setFont(font)
        self.btnProfessor.setObjectName("btnProfessor")
        self.verticalLayout_2.addWidget(self.btnProfessor)
        self.btnAluno = QtWidgets.QPushButton(self.pagina_inicial)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnAluno.setFont(font)
        self.btnAluno.setObjectName("btnAluno")
        self.verticalLayout_2.addWidget(self.btnAluno)
        self.btnSair = QtWidgets.QPushButton(self.pagina_inicial)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnSair.setFont(font)
        self.btnSair.setAutoDefault(False)
        self.btnSair.setObjectName("btnSair")
        self.verticalLayout_2.addWidget(self.btnSair)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout1.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout1, 9, 0, 1, 1)
        self.stackedWidget.addWidget(self.pagina_inicial)
        self.pagina_cadastro = QtWidgets.QWidget()
        self.pagina_cadastro.setObjectName("pagina_cadastro")
        self.stackedWidget.addWidget(self.pagina_cadastro)
        self.pagina_cadastro_aluno = QtWidgets.QWidget()
        self.pagina_cadastro_aluno.setObjectName("pagina_cadastro_aluno")
        self.stackedWidget.addWidget(self.pagina_cadastro_aluno)
        self.pagina_login = QtWidgets.QWidget()
        self.pagina_login.setObjectName("pagina_login")
        self.stackedWidget.addWidget(self.pagina_login)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 1, 1)
        self.btnsair2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair2.setMaximumSize(QtCore.QSize(130, 25))
        self.btnsair2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnsair2.setObjectName("btnsair2")
        self.gridLayout.addWidget(self.btnsair2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.btnSair.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnProfessor.setText(_translate("MainWindow", "Professor"))
        self.btnAluno.setText(_translate("MainWindow", "Aluno"))
        self.btnSair.setText(_translate("MainWindow", "Sair"))
        self.btnsair2.setText(_translate("MainWindow", "voltar para página inicial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
