# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnescimage = QtWidgets.QPushButton(self.centralwidget)
        self.btnescimage.setGeometry(QtCore.QRect(214, 250, 111, 23))
        self.btnescimage.setObjectName("btnescimage")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(250, 280, 75, 23))
        self.btnsair.setObjectName("btnsair")
        self.lblimage = QtWidgets.QLabel(self.centralwidget)
        self.lblimage.setGeometry(QtCore.QRect(390, 150, 201, 211))
        self.lblimage.setText("")
        self.lblimage.setScaledContents(True)
        self.lblimage.setObjectName("lblimage")
        self.btnmostimage = QtWidgets.QPushButton(self.centralwidget)
        self.btnmostimage.setGeometry(QtCore.QRect(214, 220, 111, 23))
        self.btnmostimage.setObjectName("btnmostimage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnsair.clicked.connect(MainWindow.close)
        # self.btnescimage.clicked.connect(self.lblimage.hide)
        # self.btnmostimage.clicked.connect(self.lblimage.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnescimage.setText(_translate("MainWindow", "Mostrar Casa"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.btnmostimage.setText(_translate("MainWindow", "Mostrar Árvore"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
